const actionType =  {
    SAVE_NEW_PRODUCT:'SAVE_NEW_PRODUCT',
    REMOVE_PRODUCT:'REMOVE_PRODUCT',
    UPDATE_PRODUCT:'UPDATE_PRODUCT',
    SAVE_NEW_PRODUCT_LIST:'SAVE_NEW_PRODUCT_LIST',
};

export default actionType;